services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=onfly_db
      - DB_USERNAME=root
      - DB_PASSWORD=YourStrong!Passw0rd

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: YourStrong!Passw0rd
      MYSQL_DATABASE: onfly_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: